COORDINATES = {"Ykköset":     179,
               "Kakkoset":    212,
               "Kolmoset":    245,
               "Neloset":     277,
               "Viitoset":    311,
               "Kuutoset":    345,
               "Välisumma":   378,
               "1 pari":      410,
               "2 paria":     441,
               "3 samaa":     472,
               "4 samaa":     510,
               "Pieni suora": 541,
               "Suuri suora": 572,
               "Täyskäsi":    607,
               "Sattuma":     638,
               "Yatzy":       674,
               "Yhteensä":    705}
